version: 0.0
os: linux
files:
  - source: botman-slack-logger/
    destination: /opt/slack-logger/
  - source: crontab
    destination: /opt/slack-logger/
  - source: scripts/
    destination: /opt/slack-logger/scripts/
  - source: etc/
    destination: /etc/
hooks:
  BeforeInstall:
    - location: scripts/create_directories
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/restart_logging
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/install_app
      timeout: 120
      runas: root
